### ISSUE TITLE
Linux - Payment Error code -4

### ISSUE THREAD

**Issue by ultra-pool** [BuckCoin/buck#4]
sendtoaddress BUCKADDRESSHERE 2942.69991608
error code: -4
error message:
Coinbase funds can only be sent to a zaddr

**Comment by BuckCoin** [comment]
This happens when you try to send newly mined coins from the initial t address to another t address without first sending the newly mined coins to a z address. All newly mined coins must be first sent to a z address -- a process call shielding. Once the newly mined coins are sent to a z address the coins can be "spent" -- otherwise, they cannot be spent.
